//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak_Sitesi_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorum
    {
        public int yorumID { get; set; }
        public int kullaniciID { get; set; }
        public string yorumİcerik { get; set; }
        public int ilanID { get; set; }
    
        public virtual ilan ilan { get; set; }
        public virtual kullanici kullanici { get; set; }
    }
}
